# src/server/core/use_cases/fundamental.py
"""Fundamental data use cases shared by MCP tools and REST routes.

Design note
-----------
Simple gateway-delegation use cases are generated by ``_gw_usecase``.
Only functions that add business logic (orchestration, multi-step calls,
service-layer delegation) are written by hand.

Adding a new gateway-delegating use case:
    1. Make sure the method exists in _TICKER_METHODS / _MARKET_METHODS
       inside market_gateway.py.
    2. Add one line here:
           get_my_new_data = _gw_usecase("get_my_new_data")
    Done.
"""

from __future__ import annotations

import json
from typing import Any, Callable, Dict, List, Optional

from src.server.core.dependencies import Container
from src.server.domain.field_translator import translate_financial_payload
from src.server.domain.response_contract import create_data_response
from src.server.utils.logger import logger


# ---------------------------------------------------------------------------
# Canonical bridge — lazy-accessor for the canonical repository
# ---------------------------------------------------------------------------

_canonical_repo = None


def _get_canonical_repo():
    """Return the CanonicalRepository if PostgreSQL is available.

    Lazily creates one from the Container's postgres connection.
    Returns None if PostgreSQL is not configured or not connected.
    """
    global _canonical_repo
    if _canonical_repo is not None:
        return _canonical_repo
    try:
        from src.server.domain.structured_data.repositories.canonical_repository import (
            CanonicalRepository,
        )
        pg = Container.postgres()
        if pg and getattr(pg, "connected", False):
            _canonical_repo = CanonicalRepository(pg)
            return _canonical_repo
    except Exception:
        pass
    return None


def reset_canonical_repo() -> None:
    """Reset cached canonical repo (for testing)."""
    global _canonical_repo
    _canonical_repo = None


# ---------------------------------------------------------------------------
# Factory: generates a coroutine function that logs + delegates to gateway
# ---------------------------------------------------------------------------


def _gw_usecase(method: str) -> Callable:
    """Return an async function that calls gateway.<method>(symbol, **kwargs).

    The generated function's signature is:
        async (symbol: str, **kwargs) -> Dict[str, Any]
    """

    async def _fn(symbol: str, **kwargs) -> Dict[str, Any]:
        gateway = Container.market_gateway()
        logger.info(f"UseCase: {method}", symbol=symbol, **kwargs)
        return await getattr(gateway, method)(symbol, **kwargs)

    _fn.__name__ = method
    _fn.__qualname__ = f"use_cases.fundamental.{method}"
    return _fn


# ---------------------------------------------------------------------------
# Gateway-delegating use cases (one line each)
# ---------------------------------------------------------------------------

get_financials = _gw_usecase("get_financials")
get_financial_statements = _gw_usecase("get_financial_statements")
get_mainbz_info = _gw_usecase("get_mainbz_info")
get_shareholder_info = _gw_usecase("get_shareholder_info")
get_dividend_info = _gw_usecase("get_dividend_info")
get_forecast_info = _gw_usecase("get_forecast_info")
get_valuation_metrics = _gw_usecase("get_valuation_metrics")
# US fundamental
get_earnings_history = _gw_usecase("get_earnings_history")
get_cash_flow_quality = _gw_usecase("get_cash_flow_quality")
get_us_valuation_metrics = _gw_usecase("get_us_valuation_metrics")
get_us_institutional_holdings = _gw_usecase("get_us_institutional_holdings")
get_us_company_profile = _gw_usecase("get_us_company_profile")
get_us_analyst_recommendations = _gw_usecase("get_us_analyst_recommendations")
get_us_revenue_segments = _gw_usecase("get_us_revenue_segments")
get_us_insider_trading = _gw_usecase("get_us_insider_trading")
get_us_share_statistics = _gw_usecase("get_us_share_statistics")
get_us_financial_health = _gw_usecase("get_us_financial_health")


# ---------------------------------------------------------------------------
# Non-trivial use cases (hand-written — these do real orchestration)
# ---------------------------------------------------------------------------


async def get_profit_forecast(ticker: str) -> Dict[str, Any]:
    manager = Container.market_gateway()
    logger.info("UseCase: get_profit_forecast", symbol=ticker)
    return await manager.get_profit_forecast(ticker)


async def get_fundamental_analysis(ticker: str) -> Dict[str, Any]:
    """Full fundamental analysis: resolves symbol first, then calls service."""
    service = Container.fundamental_service()
    gateway = Container.market_gateway()
    resolved = await gateway.resolve_ticker(ticker)
    logger.info(
        "UseCase: get_fundamental_analysis",
        symbol=ticker,
        resolved_ticker=resolved,
    )
    return await service.get_fundamental_analysis(resolved)


# ---------------------------------------------------------------------------
# Unified financial statements entry point (response-contract aware)
# ---------------------------------------------------------------------------


async def get_stock_financial_statements(
    symbol: str,
    period: str = "all",
    periods: Optional[int] = None,
) -> Dict[str, Any]:
    """Unified financial statements with canonical-first reading.

    When canonical data exists, return it directly (high quality, validated,
    structured data).  When canonical is not available, fall back to live
    gateway call.  Response includes source attribution via
    ``source_type: "canonical" | "live"``.
    """
    import json as _json
    from src.server.domain.structured_data.canonical_reader import (
        read_canonical_financial_statements,
    )

    gateway = Container.market_gateway()
    logger.info(
        "UseCase: get_stock_financial_statements",
        symbol=symbol,
        period=period,
        periods=periods,
    )

    # --- Canonical-first bridge ---
    clean_symbol = symbol
    exchange = ""
    for prefix in ("SSE:", "SZSE:", "BSE:", "NASDAQ:", "NYSE:"):
        if symbol.startswith(prefix):
            exchange = prefix.rstrip(":")
            clean_symbol = symbol[len(prefix):]
            break

    if exchange:
        canonical = await read_canonical_financial_statements(
            dataset_key="financial_statements",
            symbol=clean_symbol,
            exchange=exchange,
        )
        if canonical is not None:
            income_q, income_a = [], []
            balance_q, balance_a = [], []
            cashflow_q, cashflow_a = [], []

            for rec in canonical:
                data = rec.get("data", {})
                rp = rec.get("report_period", "")
                is_annual = rp.endswith("1231") if rp else False
                income = data.get("income_statement", [])
                balance = data.get("balance_sheet", [])
                cashflow = data.get("cash_flow", data.get("cashflow", []))
                if is_annual:
                    income_a.extend(income if isinstance(income, list) else [income])
                    balance_a.extend(balance if isinstance(balance, list) else [balance])
                    cashflow_a.extend(cashflow if isinstance(cashflow, list) else [cashflow])
                else:
                    income_q.extend(income if isinstance(income, list) else [income])
                    balance_q.extend(balance if isinstance(balance, list) else [balance])
                    cashflow_q.extend(cashflow if isinstance(cashflow, list) else [cashflow])

            translated = translate_financial_payload({
                "income_statement": {"quarterly": income_q, "annual": income_a},
                "balance_sheet": {"quarterly": balance_q, "annual": balance_a},
                "cash_flow": {"quarterly": cashflow_q, "annual": cashflow_a},
            })

            result = create_data_response(
                data=translated,
                symbol=symbol,
                source="canonical",
                period=period,
                limit=periods,
            )
            result["source"]["source_type"] = "canonical"
            result["source"]["provider"] = canonical[0].get("provider", "canonical") if canonical else "canonical"
            logger.info("Canonical data hit", symbol=symbol, records=len(canonical))
            return result

    # --- Fallback to live gateway ---
    raw = await gateway.get_financial_statements(
        symbol, report_type=period, periods=periods
    )

    source = raw.get("source", "unknown")
    if isinstance(source, dict):
        source = source.get("provider", "unknown")

    translated = translate_financial_payload({
        "income_statement": raw.get("income_statement", {}),
        "balance_sheet": raw.get("balance_sheet", {}),
        "cash_flow": raw.get("cash_flow", {}),
    })

    result = create_data_response(
        data=translated,
        symbol=raw.get("ts_code") or raw.get("ticker") or symbol,
        source=source,
        period=period,
        limit=periods,
    )
    result["source"]["source_type"] = "live"
    return result

